services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Xima\XmTools\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Xima\XmTools\Backend\ToolbarItems\WebsiteVersionToolbarItem:
    tags:
      - name: backend.toolbar.item
